#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
RASI="$cd ~/.config/polybar/rofi/powermenu.rasi"

# Theme Elements
prompt="`hostname` (`echo $DESKTOP_SESSION`)"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1=" Lock"
	option_2=" Logout"
	option_3=" Suspend"
	option_4=" Hibernate"
	option_5=" Reboot"
	option_6=" Shutdown"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI} \
        -hover-select \
        -me-select-entry '' \
        -me-accept-entry MousePrimary
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}


# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		betterlockscreen --lock
        ;;
    $option_2)
		pkill -KILL -u "$USER"
        ;;
    $option_3)
		systemctl suspend
        ;;
    $option_4)
		systemctl hibernate
        ;;
    $option_5)
		systemctl reboot
        ;;
    $option_6)
		systemctl poweroff
        ;;
esac
